### ISSUE TITLE
合计金额识别错误BUG

### ISSUE THREAD

**Issue by irezm** [sanluan/einvoice#1]
com.sanluan.einvoice.service.InvoiceExtractor 
第79行应当修改：
修改前：Matcher matcher = pattern.matcher(fullText);
修改后：Matcher matcher = pattern.matcher(allText);

因为使用未处理文本导致合计金额识别不准确

**Comment by sanluan** [comment]
感谢 我验证下

**Comment by awwaawwa** [comment]
这句话应该是用来兜底的，如果这样修改， #2 中的发票就无法识别合计金额了。
