### ISSUE TITLE
Whitelabel Error Page

### ISSUE THREAD

**Issue by xigxmmbc** [sanluan/einvoice#13]
用idea运行项目，用edge浏览器访问http://localhost:9090/invoice（application.properties中端口改为9090了）报错

Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Tue Jul 23 22:31:22 CST 2024
There was an unexpected error (type=Not Found, status=404).

**Comment by sanluan** [comment]
程序源码中并没有页面,http://www.heycore.com/invoice.html 这里的页面可以下载到本地使用 把页面里面接口地址改了就行
