### ISSUE TITLE
商品名称中带有%的发票解析失败

### ISSUE THREAD

**Issue by awwaawwa** [sanluan/einvoice#2]
出问题的发票文件：[011002000911-12095199.pdf](https://github.com/sanluan/einvoice/files/7880844/011002000911-12095199.pdf)
此发票中货物名称：*日用杂品*润本(RUNBEN)驱蚊 液婴儿 110ml 防蚊 驱蚊水 驱防蚊喷 雾 防蚊液 蚊虫叮咬花露水7%驱
在 com.sanluan.einvoice.service.InvoiceExtractor 文件 318-321 行中，有用到税率中的“%”来判定是否为下一商品名称，但是这个商品名称自带“%”。然后就会炸掉。

**Comment by awwaawwa** [comment]
您可以尝试在这个if中加入这样一句话，来检查%左右是否都有数字
&& (!detailString.contains("%") || detailString.matches("\\S+[.\\d-]+%[.\\d-]+\\S*"))

**Comment by awwaawwa** [comment]
这张发票的合计解析也是错误的，我尝试将60行的正则表达式 "合计¥?(?<amount>[^ \\f\\n\\r\\t\\v\\*]*)(?:¥?(?<taxAmount>\\S*)|\\*+)\\s" 第二个¥后的？改成了+然后就能用了，但是没做进一步的测试

**Comment by sanluan** [comment]
修改了
